# Generated by Django 5.0 on 2024-07-22 21:55

import GutenReaderApp.models
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('author', models.CharField(max_length=100)),
                ('language', models.CharField(max_length=50)),
                ('translater', models.CharField(blank=True, default='', max_length=100)),
                ('view_count', models.IntegerField(default=0)),
                ('do_recommend_count', models.IntegerField(default=0)),
                ('do_not_recommend_count', models.IntegerField(default=0)),
                ('date_added', models.DateTimeField(default=django.utils.timezone.now)),
                ('project_gutenberg_id', models.IntegerField(default=-1)),
                ('verified_public_domain', models.BooleanField(default=False)),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to=GutenReaderApp.models.cover_directory_path)),
                ('full_text', models.TextField()),
                ('chapter_titles', models.JSONField(default=list)),
                ('chapter_divisions', models.JSONField(default=list)),
                ('section_indices', models.JSONField(blank=True, default=list)),
            ],
        ),
        migrations.CreateModel(
            name='TextUpload',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('book_file', models.FileField(upload_to='book_files/')),
            ],
        ),
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=40)),
                ('books', models.ManyToManyField(to='GutenReaderApp.book')),
            ],
        ),
    ]
