# Generated by Django 5.0 on 2024-08-12 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GutenReaderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subjecttag',
            name='num_books',
            field=models.IntegerField(default=0),
        ),
    ]
