# Generated by Django 5.0 on 2024-04-10 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GutenReaderApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='do_not_recommend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='do_recommend_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='book',
            name='section_indices',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='book',
            name='view_count',
            field=models.IntegerField(default=0),
        ),
    ]
