# Generated by Django 5.0 on 2024-04-21 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GutenReaderApp', '0003_book_date_added_book_project_gutenberg_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubjectTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(max_length=40)),
                ('books', models.ManyToManyField(to='GutenReaderApp.book')),
            ],
        ),
    ]
