# Generated by Django 5.0 on 2024-04-22 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GutenReaderApp', '0004_subjecttag'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='translater',
            field=models.CharField(default='', max_length=100),
        ),
    ]
