# Generated by Django 5.0 on 2024-05-14 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GutenReaderApp', '0005_book_translater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='translater',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
