# Generated by Django 5.0 on 2024-05-14 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GutenReaderApp', '0006_alter_book_translater'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='section_indices',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
