# Generated by Django 5.0 on 2024-06-05 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GutenReaderApp', '0007_alter_book_section_indices'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='book_covers/'),
        ),
    ]
