# Generated by Django 5.0 on 2024-07-22 00:17

import GutenReaderApp.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('GutenReaderApp', '0008_book_book_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='verified_public_domain',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to=GutenReaderApp.models.cover_directory_path),
        ),
    ]
